version: "3.4"
services:
  object-detection-streamlit:
    tty: true
    image: "eduardomatoss/object-detection-streamlit"
    stdin_open: true
    build:
      context: .
      target: "development"
    volumes:
      - ".:/app"
    networks:
      - network

networks:
  network:
    driver: bridge